version: "3.8"
name: ScanTextify

services:

  database:
    image: mysql:8.0-bookworm
    restart: always
    env_file:
      - path: ./database-docker.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  website:
    build: ./
    ports:
      - '5500:5500'
    expose:
      - 5500
    env_file:
      - path: ./.env
    depends_on:
      database:
        condition: service_healthy

volumes:
    db_data:
